fix Jenkinsfile*

diff --git a/CI-CD/Jenkins/automate-nightly-backup/python-app/Jenkinsfile.backup b/CI-CD/Jenkins/automate-nightly-backup/python-app/Jenkinsfile.backup
--- a/CI-CD/Jenkins/automate-nightly-backup/python-app/Jenkinsfile.backup
+++ b/CI-CD/Jenkins/automate-nightly-backup/python-app/Jenkinsfile.backup
@@ -1,30 +1,39 @@
 pipeline {
-    agent any 
+    agent any
     environment {
-        APP_DIR = "python-app/artifacts"
+        APP_DIR = "artifacts"
         S3_BUCKET_PATH = "s3://python-app-nightly-backup/python-project/"
     }
 
     stages {
+        stage('Retrieve Latest Build') {
+            steps {
+                // Отримуємо артефакти з останнього успішного build job
+                copyArtifacts(
+                    projectName: 'build-job-name',  // замініть на реальну назву Pipeline 1
+                    filter: 'artifacts/*.tar.gz',
+                    selector: lastSuccessful()
+                )
+            }
+        }
+
         stage('Backup build to S3') {
             steps {
                 dir(APP_DIR) {
                     script {
                         docker.image('amazon/aws-cli:latest').inside {
                             withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
-                                sh '''
-                                    LATEST_BUILD=$(ls -t *.tar.gz 2>/dev/null | head -1)
+                                sh '''#!/bin/bash
+                                LATEST_BUILD=$(ls -t *.tar.gz 2>/dev/null | head -1)
 
-                                    if [ -z "$LATEST_BUILD" ]; then
-                                        echo "❌ ERROR: No build files found in $APP_DIR. Stopping backup."
-                                        exit 1
-                                    fi
+                                if [ -z "$LATEST_BUILD" ]; then
+                                    echo "❌ ERROR: No build files found in $APP_DIR. Stopping backup."
+                                    exit 1
+                                fi
 
-                                    echo "✅ Found latest build: $LATEST_BUILD. Uploading to $S3_BUCKET_PATH"
-                                    
-                                    aws s3 cp "$LATEST_BUILD" "${S3_BUCKET_PATH}" --acl public-read
-
-                                    echo "✅ Backup completed successfully."
+                                echo "✅ Found latest build: $LATEST_BUILD. Uploading to $S3_BUCKET_PATH"
+                                aws s3 cp "$LATEST_BUILD" "${S3_BUCKET_PATH}" --acl public-read
+                                echo "✅ Backup completed successfully."
                                 '''
                             }
                         }
